#ссылка на вебхук выдачи вип
#можете оставить пустым если не планируете использовать (работает без HMAC)
WEBHOOK_URL = ""

#ссылка на REST API
REST_API_URL = ""

#токен авторизации REST_API
AUTH_TOKEN = ""

#токен бота в дискорде
BOT_TOKEN = ""

#ID роли в дискорде, которой можно будет использовать /add
ROLE = 12345